<?php

$table1_items = array(
    "Choisissez votre option",
    "Évaluation des besoins",
    "Passeport-emploi et plan d'action",
    "Professions et métiers réglementés",
    "Reconnaissance d'acquis et des compétences (RAC)",
    "Subvention salariale"
);

$table2_items = array(
    "Choisissez votre option",
    "Word débutant",
    "Word intermédiaire",
    "Excel débutant",
    "Excel intermédiaire",
    "Sage 50 débutant",
    "Sage 50 intermédiaire",
    "Acomba débutant",
    "Acomba intermédiaire",
    "AutoCAD débutant",
    "AutoCAD intermédiaire",
    "SolidWorks",
    "Powerpoint",
    "Internet et réseaux sociaux"
);

$table3_items = array(
    "Choisissez votre option",
    "Stage de perfectionnement",
    "Stage en enterprise"
);

$table4_items = array(
    "Choisissez votre option",
    "Cours de français",
    "Cours d'anglais",
    "Permis de conduire"
);

$table5_items = array(
    "Choisissez votre option",
    "Atelier d'employabilité",
    "Les valeurs communes québécoises"
);

$table6_items = array(
    "Choisissez votre option",
    "Immersion française en milieu de travail",
    "Parcours intégration emploi",
    "Soutien à la personne en milieu de vie",
    "Réactive-toi/Valorise-toi",
    "Projet de sensibilisation à la diversité culturelle"
);

$cle = array(
    "Choisissez votre option",
    "CLE de Sainte-Foy",
    "CLE de Charlesbourg",
    "CLE de Beauport",
    "CLE de La Cité",
    "CLE de Lebourgneuf"
);

$situation = array(
    "Choisissez votre option",
    "Aux études",
    "Sans emploi",
    "Emploi à temps partiel",
    "En francisation",
    "En recherche d'emploi",
    "Emploi à temps plein",
    "Rettaité",
    "N/A"
);

$stats = array(
    "Choisissez votre option",
    "Citoyen canadien",
    "Résident permanent",
    "Travailleur temporaire",
    "Étudiant étranger",
    "Demandeur d'asile",
    "Résident temporaire avec CSQ",
    "Réfugié"
);

$statut = array(
    "Choisissez votre option",
    "Bénévole",
    "Participant",
    "Bénéficiaire",
);

$ages = array(
    "Choisissez votre option",
    "15-30 ans",
    "31-50 ans",
    "50 ans +",
);


$countries = array(
    "Choisissez votre option",
    "Afghanistan",
    "Afrique du Sud",
    "Albanie",
    "Algérie",
    "Allemagne",
    "Andorre",
    "Angola",
    "Anguilla",
    "Antarctique",
    "Antigua-et-Barbuda",
    "Antilles Néerlandaises",
    "Arabie Saoudite",
    "Argentine",
    "Arménie",
    "Aruba",
    "Australie",
    "Autriche",
    "Azerbaïdjan",
    "Bahamas",
    "Bahreïn",
    "Bangladesh",
    "Barbade",
    "Bélarus",
    "Belgique",
    "Belize",
    "Bénin",
    "Bermudes",
    "Bhoutan",
    "Bolivie",
    "Bosnie-Herzégovine",
    "Botswana",
    "Brésil",
    "Brunéi Darussalam",
    "Bulgarie",
    "Burkina Faso",
    "Burundi",
    "Cambodge",
    "Cameroun",
    "Canada",
    "Cap-vert",
    "Chili",
    "Chine",
    "Chypre",
    "Colombie",
    "Comores",
    "Costa Rica",
    "Côte d'Ivoire",
    "Croatie",
    "Cuba",
    "Danemark",
    "Djibouti",
    "Dominique",
    "Égypte",
    "El Salvador",
    "Émirats Arabes Unis",
    "Équateur",
    "Érythrée",
    "Espagne",
    "Estonie",
    "États Fédérés de Micronésie",
    "États-Unis",
    "Éthiopie",
    "Fédération de Russie",
    "Fidji",
    "Finlande",
    "France",
    "Gabon",
    "Gambie",
    "Géorgie",
    "Géorgie du Sud et les Îles Sandwich du Sud",
    "Ghana",
    "Gibraltar",
    "Grèce",
    "Grenade",
    "Groenland",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guinée",
    "Guinée Équatoriale",
    "Guinée-Bissau",
    "Guyana",
    "Guyane Française",
    "Haïti",
    "Honduras",
    "Hong-Kong",
    "Hongrie",
    "Île Bouvet",
    "Île Christmas",
    "Île de Man",
    "Île Norfolk",
    "Îles (malvinas) Falkland",
    "Îles Åland",
    "Îles Caïmanes",
    "Îles Cocos (Keeling)",
    "Îles Cook",
    "Îles Féroé",
    "Îles Heard et Mcdonald",
    "Îles Mariannes du Nord",
    "Îles Marshall",
    "Îles Mineures Éloignées des États-Unis",
    "Îles Salomon",
    "Îles Turks et Caïques",
    "Îles Vierges Britanniques",
    "Îles Vierges des États-Unis",
    "Inde",
    "Indonésie",
    "Iraq",
    "Irlande",
    "Islande",
    "Israël",
    "Italie",
    "Jamahiriya Arabe Libyenne",
    "Jamaïque",
    "Japon",
    "Jordanie",
    "Kazakhstan",
    "Kenya",
    "Kirghizistan",
    "Kiribati",
    "Koweït",
    "L'ex- République Yougoslave de Macédoine",
    "Lesotho",
    "Lettonie",
    "Liban",
    "Libéria",
    "Liechtenstein",
    "Lituanie",
    "Luxembourg",
    "Macao",
    "Madagascar",
    "Malaisie",
    "Malawi",
    "Maldives",
    "Mali",
    "Malte",
    "Maroc",
    "Martinique",
    "Maurice",
    "Mauritanie",
    "Mayotte",
    "Mexique",
    "Monaco",
    "Mongolie",
    "Montserrat",
    "Mozambique",
    "Myanmar",
    "Namibie",
    "Nauru",
    "Népal",
    "Nicaragua",
    "Niger",
    "Nigéria",
    "Niué",
    "Norvège",
    "Nouvelle-Calédonie",
    "Nouvelle-Zélande",
    "Oman",
    "Ouganda",
    "Ouzbékistan",
    "Pakistan",
    "Palaos",
    "Panama",
    "Papouasie-Nouvelle-Guinée",
    "Paraguay",
    "Pays-Bas",
    "Pérou",
    "Philippines",
    "Pitcairn",
    "Pologne",
    "Polynésie Française",
    "Porto Rico",
    "Portugal",
    "Qatar",
    "République Arabe Syrienne",
    "République Centrafricaine",
    "République de Corée",
    "République de Moldova",
    "République Démocratique du Congo",
    "République Démocratique Populaire Lao",
    "République Dominicaine",
    "République du Congo",
    "République Islamique d'Iran",
    "République Populaire Démocratique de Corée",
    "République Tchèque",
    "République-Unie de Tanzanie",
    "Réunion",
    "Roumanie",
    "Royaume-Uni",
    "Rwanda",
    "Sahara Occidental",
    "Saint-Kitts-et-Nevis",
    "Saint-Marin",
    "Saint-Pierre-et-Miquelon",
    "Saint-Siège (état de la Cité du Vatican)",
    "Saint-Vincent-et-les Grenadines",
    "Sainte-Hélène",
    "Sainte-Lucie",
    "Samoa",
    "Samoa Américaines",
    "Sao Tomé-et-Principe",
    "Sénégal",
    "Serbie-et-Monténégro",
    "Seychelles",
    "Sierra Leone",
    "Singapour",
    "Slovaquie",
    "Slovénie",
    "Somalie",
    "Soudan",
    "Sri Lanka",
    "Suède",
    "Suisse",
    "Suriname",
    "Svalbard etÎle Jan Mayen",
    "Swaziland",
    "Tadjikistan",
    "Taïwan",
    "Tchad",
    "Terres Australes Françaises",
    "Territoire Britannique de l'Océan Indien",
    "Territoire Palestinien Occupé",
    "Thaïlande",
    "Timor-Leste",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinité-et-Tobago",
    "Tunisie",
    "Turkménistan",
    "Turquie",
    "Tuvalu",
    "Ukraine",
    "Uruguay",
    "Vanuatu",
    "Venezuela",
    "Viet Nam",
    "Wallis et Futuna",
    "Yémen",
    "Zambie",
    "Zimbabwe"
);